App/Hra.App/Controllers/ClienteController.cs
using Hra.App.Models;
using Hra.App.Servicio;
using Hra.Application.DTO;
using Hra.Domain.Entity;
using Hra.Infraestructure.Data;
using Hra.Transversal.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hra.App.Controllers
{
    public class ClienteController : Controller
    {
        private readonly BAMBUContext contexto;
        private readonly IConstante constante;
        private readonly IAlmacenadorArchivos almacenadorArchivos;

        public ClienteController(BAMBUContext contexto, IConstante constante, IAlmacenadorArchivos almacenadorArchivos)
        {
            this.contexto = contexto;
            this.constante = constante;
            this.almacenadorArchivos = almacenadorArchivos;
        }
        public async Task<IActionResult> Index(int pPersonaId = 0)
        {
            if (pPersonaId == 0)
                return View();

            var persona = await contexto.Persona.FirstOrDefaultAsync(x => x.PersonaId == pPersonaId);

            var mensaje = await (from p in contexto.Mensaje
                                 join vt in (contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Nivel)) on p.NivelId equals vt.ItemId
                                 where p.MiembroId == pPersonaId
                                 orderby p.Fecha descending
                                 select new ListarMensajeDto()
                                 {
                                     Fecha = p.Fecha,
                                     Nota = p.Nota,
                                     MensajeId = p.MensajeId,
                                     Nivel = vt.Denominacion
                                 }).ToListAsync();

            ViewBag.PersonaId = pPersonaId;
            ViewBag.NombreCompleto = persona.NombreCompleto;
            ViewBag.cboNivel = await contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Nivel && x.ItemId > 0)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();
            ViewBag.cboEvidencia = await contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Evidencia && x.ItemId > 0)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();

            return View(mensaje);
        }

        public async Task<IActionResult> Listar(string pBuscar = "")
        {
            var lstPersona = new List<ListarMiembroDto>();
            if (!string.IsNullOrEmpty(pBuscar) && pBuscar.Trim().Length > 0)
                lstPersona = await (from x in contexto.Miembro
                                    join vt in (contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.EstadoMiembro)) on x.EstadoId equals vt.ItemId
                                    join n in (contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Nivel)) on x.NivelId equals n.ItemId
                                    where x.Persona.NombreCompleto.Contains(pBuscar) || x.Grupo.Denominacion.Contains(pBuscar)
                                    select new ListarMiembroDto
                                    {
                                        MiembroId = x.MiembroId,
                                        PersonaId = x.PersonaId,
                                        Dni = x.Persona.NumeroDocumento,
                                        Miembro = x.Persona.NombreCompleto,
                                        Celular = x.Persona.Celular,
                                        Correo = x.Persona.Email,
                                        Grupo = x.Grupo.Denominacion,
                                        Nivel = n.Denominacion,
                                        Estado = vt.Denominacion,
                                        EstadoId = x.EstadoId,
                                        NivelId = x.NivelId
                                    }).ToListAsync();
            else
                lstPersona = await (from x in contexto.Miembro
                                    join vt in (contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.EstadoMiembro)) on x.EstadoId equals vt.ItemId
                                    join n in (contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Nivel)) on x.NivelId equals n.ItemId
                                    select new ListarMiembroDto
                                    {
                                        MiembroId = x.MiembroId,
                                        PersonaId = x.PersonaId,
                                        Dni = x.Persona.NumeroDocumento,
                                        Miembro = x.Persona.NombreCompleto,
                                        Celular = x.Persona.Celular,
                                        Correo = x.Persona.Email,
                                        Grupo = x.Grupo.Denominacion,
                                        Nivel = n.Denominacion,
                                        Estado = vt.Denominacion,
                                        EstadoId = x.EstadoId,
                                        NivelId = x.NivelId
                                    }).Take(10).OrderByDescending(x => x.PersonaId).ToListAsync();

            return View(lstPersona);
        }
        public async Task<IActionResult> Editar(int id = 0)
        {
            var persona = new Persona()
            {
                Activo = true
            };
            if (id > 0)
                persona = await contexto.Persona.FirstOrDefaultAsync(x => x.PersonaId == id);

            ViewBag.TokenApiPeru = constante.TokenApiPeru;
            ViewBag.cboEstadoCivil = await contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.EstadoCivil && x.ItemId > 0)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();
            ViewBag.cboApoderadoParentesco = await contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.ApoderadoParentesco && x.ItemId > 0)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();
            ViewBag.cboTipoAlimentacion = await contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.TipoAlimentacion && x.ItemId > 0)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();
            //ViewBag.cboEstado = await contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.EstadoMiembro && x.ItemId > 0)
            //    .Select(x => new SelectListItem
            //    {
            //        Text = x.Denominacion,
            //        Value = x.ItemId.ToString()
            //    }).ToListAsync();
            //ViewBag.cboGrupo = await contexto.Grupo
            //    .Select(x => new SelectListItem
            //    {
            //        Text = x.Denominacion,
            //        Value = x.GrupoId.ToString()
            //    }).ToListAsync();
            //ViewBag.cboNivel = await contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Nivel && x.ItemId > 0)
            //    .Select(x => new SelectListItem
            //    {
            //        Text = x.Denominacion,
            //        Value = x.ItemId.ToString()
            //    }).ToListAsync();

            if (persona.FechaNacimiento.HasValue)
            {
                int edad = DateTime.Today.AddTicks(-persona.FechaNacimiento.Value.Ticks).Year - 1;
                ViewBag.Edad = edad;
            }
            else
                ViewBag.Edad = 0;

            if (persona.PersonaReferenciaId == null)
                ViewBag.PersonaReferencia = string.Empty;
            else
                ViewBag.PersonaReferencia = contexto.Persona
                .FirstOrDefault(x => x.PersonaId == persona.PersonaReferenciaId).NombreCompleto;

            return View(persona);
        }

        [HttpGet]
        public async Task<JsonResult> BuscarClienteAutocomplete(string term)
        {
            var qry = from p in contexto.Persona
                      where p.Activo && (p.NombreCompleto.Contains(term) || p.NumeroDocumento.Contains(term))
                      orderby p.NombreCompleto
                      select new { id = p.PersonaId, text = p.NumeroDocumento + " " + p.NombreCompleto };
            return Json(await qry.Take(10).ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Guardar(Persona miembro)
        {
            miembro.ApePaterno = miembro.ApePaterno.Trim().ToUpper();
            miembro.ApeMaterno = miembro.ApeMaterno.Trim().ToUpper();
            miembro.Nombre = miembro.Nombre.Trim().ToUpper();
            miembro.NombreCompleto = miembro.ApePaterno + " " + miembro.ApeMaterno + " " + miembro.Nombre;
            miembro.FechaReg = DateTime.Now;

            if (miembro.PersonaId > 0)
                contexto.Persona.Update(miembro);
            else
                contexto.Persona.Add(miembro);

            await contexto.SaveChangesAsync();


            return RedirectToAction("Listar");
        }
        [HttpPost]
        public async Task<IActionResult> CrearPersona(string pDni, string pNombre, string pPaterno, string pMaterno)
        {
            pPaterno = pPaterno.Trim().ToUpper();
            pMaterno = pMaterno.Trim().ToUpper();
            pNombre = pNombre.Trim().ToUpper();

            var existepersona = await contexto.Persona.AnyAsync(x => x.NumeroDocumento == pDni);
            if (existepersona)

App/Hra.App/Controllers/ProcesoController.cs
using Hra.App.Models;
using Hra.App.Servicio;
using Hra.Application.DTO;
using Hra.Domain.Entity;
using Hra.Infraestructure.Data;
using Hra.Transversal.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hra.App.Controllers
{
    public class ProcesoController : Controller
    {
        private readonly BAMBUContext contexto;
        private readonly IConstante constante;
        private readonly IAlmacenadorArchivos almacenadorArchivos;
        private readonly string _contenedor = "storage";
        public ProcesoController(BAMBUContext contexto, IConstante constante, IAlmacenadorArchivos almacenadorArchivos)
        {
            this.contexto = contexto;
            this.constante = constante;
            this.almacenadorArchivos = almacenadorArchivos;
        }
        public async Task<IActionResult> Index(int pMiembroId)
        {
            var miembro = await contexto.Miembro.Include(x => x.Persona).Include(x => x.Grupo)
                .FirstOrDefaultAsync(x => x.MiembroId == pMiembroId);
            var nivel = await contexto.ValorTabla.FirstOrDefaultAsync(x => x.TablaId == Constante.Tabla.Nivel && x.ItemId == miembro.NivelId);
            var Estado = await contexto.ValorTabla.FirstOrDefaultAsync(x => x.TablaId == Constante.Tabla.EstadoMiembro && x.ItemId == miembro.EstadoId);

            var mensaje = await (from p in contexto.Mensaje
                                 join vt in (contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Nivel)) on p.NivelId equals vt.ItemId
                                 where p.MiembroId == pMiembroId
                                 orderby p.Fecha descending
                                 select new ListarMensajeDto()
                                 {
                                     Fecha = p.Fecha,
                                     Nota = p.Nota,
                                     MensajeId = p.MensajeId,
                                     Nivel = vt.Denominacion
                                 }).ToListAsync();

            var archivos = await (from p in contexto.Archivo
                                  join vt in (contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Evidencia)) on p.EvidenciaId equals vt.ItemId
                                  where p.MiembroId == pMiembroId
                                  orderby p.Fecha descending
                                  select new ListarArchivoDto()
                                  {
                                      Fecha = p.Fecha,
                                      ArchivoId = p.ArchivoId,
                                      Evidencia = vt.Denominacion,
                                      Archivo = p.Nombre
                                  }).ToListAsync();
            var pago = await contexto.MiembroPago.Where(x => x.MiembroId == pMiembroId).ToListAsync();

            ViewBag.MiembroId = pMiembroId;
            ViewBag.NombreCompleto = miembro.Persona.NombreCompleto
                + " [" + miembro.Grupo.Denominacion + "-" + nivel.Denominacion + "]"
                + " ESTADO: " + Estado.Denominacion;
            var tallerid = miembro.Grupo.TallerId.ToString();
            ViewBag.cboNivel = await contexto.ValorTabla
                .Where(x => x.TablaId == Constante.Tabla.Nivel && x.ItemId > 0 && x.Valor == tallerid)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();
            ViewBag.cboEvidencia = await contexto.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Evidencia && x.ItemId > 0)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();

            return View(new ProcesoMiembro
            {
                Mensajes = mensaje,
                Archivos = archivos,
                Pago = pago.Where(x => x.IndPago == true).ToList(),
                PagoCompromiso = pago.Where(x => x.IndPago == false).ToList()
            });
        }
        public class ProcesoMiembro
        {
            public List<ListarMensajeDto> Mensajes { get; set; }
            public List<ListarArchivoDto> Archivos { get; set; }
            public List<MiembroPago> PagoCompromiso { get; set; }
            public List<MiembroPago> Pago { get; set; }
        }
        [HttpPost]
        public async Task<IActionResult> GuardarMensaje(Mensaje mensaje)
        {
            mensaje.Fecha = DateTime.Now;
            contexto.Mensaje.Add(mensaje);
            await contexto.SaveChangesAsync();
            return RedirectToAction("Index", new { pMiembroId = mensaje.MiembroId });
        }

        [HttpPost]
        public async Task<IActionResult> GuardarPago(MiembroPago pago)
        {
            contexto.MiembroPago.Add(pago);
            await contexto.SaveChangesAsync();
            return RedirectToAction("Index", new { pMiembroId = pago.MiembroId });
        }

        public async Task<ActionResult> EliminarMensaje(int pMensajeId)
        {
            var m = await contexto.Mensaje.FindAsync(pMensajeId);
            if (m != null)
            {
                contexto.Mensaje.Remove(m);
                await contexto.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index), new { pMiembroId = m.MiembroId });
        }
        public async Task<ActionResult> EliminarArchivo(int pArchivoId)
        {
            var m = await contexto.Archivo.FindAsync(pArchivoId);
            if (m != null)
            {
                if (!string.IsNullOrEmpty(m.Nombre))
                    await almacenadorArchivos.BorrarArchivo(m.Nombre, _contenedor);

                contexto.Archivo.Remove(m);
                await contexto.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index), new { pMiembroId = m.MiembroId });
        }
        public async Task<ActionResult> EliminarPagoMiembro(int pMiembroPagoId)
        {
            var m = await contexto.MiembroPago.FindAsync(pMiembroPagoId);
            if (m != null)
            {
                contexto.MiembroPago.Remove(m);
                await contexto.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index), new { pMiembroId = m.MiembroId });
        }

        [HttpPost]
        public async Task<IActionResult> GuardarArchivo(IFormFile file, Archivo archivo)
        {
            if (file != null)
            {
                var extension = Path.GetExtension(file.FileName).ToLower();
                using (var memorystream = new MemoryStream())
                {
                    await file.CopyToAsync(memorystream);
                    var contenido = memorystream.ToArray();
                    archivo.Nombre = await almacenadorArchivos.GuardarArchivo(contenido, extension, _contenedor, file.ContentType);
                }
            }

            archivo.Fecha = DateTime.Now;
            contexto.Archivo.Add(archivo);
            await contexto.SaveChangesAsync();
            return RedirectToAction("Index", new { pMiembroId = archivo.MiembroId });
        }
    }
}

App/Hra.App/Views/Cliente/Index.cshtml
@model List< Hra.Application.DTO.ListarMensajeDto>
<div class="row">
    <div class="col-sm-12 col-md-6">
        <div class="mb-3">
            <div class="mb-3 ajax-select mt-3 mt-lg-0">
                <div class="input-group">
                    <select id="cboBuscarCliente" class="form-control" aria-describedby="btnCrearPersona"></select>
                    <button class="btn btn-primary" type="button" id="btnCrearPersona">
                        <i class="bx bx-user-plus font-size-16 align-middle"></i>
                        Nuevo
                    </button>
                </div>
            </div>
        </div>
    </div>
    @if (ViewBag.PersonaId > 0)
    {
        <div id="pnlParticipante" class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title mb-4">@ViewBag.NombreCompleto</h4>
                    <form method="post" asp-action="GuardarMensaje">
                        <div class="row">
                            <input type="hidden" name="PersonaId" value="@ViewBag.PersonaId" />
                            <div class="col-auto">
                                <select class="form-select" name="NivelId" asp-items="@ViewBag.cboNivel">
                                </select>
                            </div>
                            <div class="col">
                                <div class="position-relative">
                                    <input type="text" name="Nota" class="form-control rounded chat-input" placeholder="Registro de Notas y Llamadas...">

                                </div>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-primary chat-send w-md waves-effect waves-light"><span class="d-none d-sm-inline-block me-2">Registrar</span> <i class="mdi mdi-send"></i></button>
                            </div>
                        </div>
                    </form>
                    <table class="table table-hover table-bordered  mt-3">
                        <thead class="table-light">
                            <tr>
                                <th>Fecha</th>
                                <th>Nivel</th>
                                <th>Nota</th>                                
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td style="width:200px">
                                        @item.Fecha
                                    </td>
                                    <td style="width:200px">
                                        @item.Nivel
                                    </td>
                                    <td>
                                        @item.Nota
                                    </td>                                    
                                    <td style="width:100px">
                                        <a href="javascript: void(0);" class="text-danger p-1"><i class="bx bxs-trash"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br>
                    <form>
                        <div class="row">
                            <div class="col-auto">
                                <select class="form-select" name="EvidenciaId" asp-items="@ViewBag.cboEvidencia">
                                </select>
                            </div>
                            <div class="col">
                                <div class="position-relative">
                                    <input type="file" class="form-control rounded chat-input" placeholder="Registra un Archivo...">

                                </div>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-primary chat-send w-md waves-effect waves-light"><span class="d-none d-sm-inline-block me-2">Registrar</span> <i class="mdi mdi-send"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }

</div>

@section scripts{
<script>
    $(document).ready(function (){
        $("#cboBuscarCliente").select2({
            language: "es",
            ajax:{
                type:"GET",
                url:"@Url.Action("BuscarClienteAutocomplete","Cliente")",
                dataType:"json",
                delay:200,
                processResults:function(results){
                    return {results};
                },
                cache:true
            },
            placeholder:'Buscar por apellidos o dni',
            minimumInputLength:2
        });
    });

    $('#cboBuscarCliente').on('select2:select', function (e) {
        var data = e.params.data;
        if(data.selected){
            //$("#pnlParticipante").show();
            window.location = '@Url.Action("Index", "Cliente")' + "?pPersonaId=" + data.id;
        }
    });

</script>
}

App/Hra.App/Views/Cliente/Listar.cshtml
@model IEnumerable<Hra.Application.DTO.ListarMiembroDto>

<h1>Miembros</h1>
<div class="row mb-4">
    <div class="col-sm-6">
        <form asp-action="Listar">
            <input name="pBuscar" class="form-control" placeholder="Buscar por Apellidos luego <ENTER>" />
        </form>
    </div>
    <div class="col-sm-6">
        <div class="text-sm-end mt-2 mt-sm-0">
            <a type="button" href="@Url.Action("Editar","Cliente", new { id=0  })" class="btn btn-primary">
                <i class="mdi mdi-plus-outline me-1"></i>Nuevo
            </a>
        </div>
    </div>
</div>

<table class="table table-hover table-bordered  mb-0">
    <thead class="table-light">
        <tr>
            <th>Grupo</th>
            <th>DNI</th>
            <th>Nombre Completo</th>
            <th>Email</th>
            <th>Celular</th>
            <th>Estado</th>
            <th>Nivel</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Grupo</td>
                <td>@item.Dni</td>
                <td>@item.Miembro</td>
                <td>@item.Correo</td>
                <td>@item.Celular</td>
                <td>@item.Estado</td>
                <td>@item.Nivel</td>
                <td>
                    <a type="button" href="@Url.Action("Editar","Cliente", new { id=item.PersonaId  })" class="btn btn-primary btn-sm">Datos</a>
                    <a type="button" href="@Url.Action("Index","Proceso", new { pMiembroId=item.MiembroId  })" class="btn btn-primary btn-sm">Proceso</a>
               </td>
            </tr>
        }
    </tbody>
</table>

App/Hra.App/Views/Cliente/MiembroFoto.cshtml
@model List<Hra.Domain.Entity.MiembroFoto>
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">@ViewBag.NombreCompleto</h4>
                <p class="card-title-desc">Galería de Imagenes </p>
                <form method="post" asp-action="GuardarFoto" enctype="multipart/form-data">
                    <div class="row">
                        <input type="hidden" name="pMiembroId" value="@ViewBag.MiembroId" />
                        <div class="col">
                            <div class="position-relative">
                                <input type="file" required name="file" accept="image/png,image/jpeg" class="form-control rounded chat-input" placeholder="Seleccionar Imagen...">
                            </div>
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-primary chat-send w-md waves-effect waves-light"><span class="d-none d-sm-inline-block me-2">Subir Imagen</span> <i class="mdi mdi-cloud-upload"></i></button>
                        </div>
                    </div>
                </form>
                <hr />
                <div class="popup-gallery d-flex flex-wrap">

                    @foreach (var item in Model)
                    {
                        <div class="row m-0 p-0">
                            <div class="col-12 m-0 p-0">
                                <a href="~/galeria/@item.Foto" title="Bambu">
                                    <div class="img-fluid">
                                        <img src="~/galeria/@item.Foto" alt="" width="250">
                                    </div>
                                </a>
                            </div>
                            <div class="col-12 m-0 p-0">
                                <form action="@Url.Action("EliminarFoto","Cliente")" method="get">
                                    <input type="hidden" name="pMiembroFotoId" value="@item.MiembroFotoId">
                                    <button type="submit" class="btn btn-danger btn-sm">X</button>
                                </form>
                            </div>
                        </div>
                    }

                </div>

            </div>
        </div>
    </div>
</div>

@section scripts{
<script>
    $(function(){
        $(".popup-gallery").magnificPopup({
            delegate:"a",
            type:"image",
            mainClass:"mfp-img-mobile",
            gallery:{enabled:!0,navigateByImgClick:!0,preload:[0,1]}
        });
    });

</script>
}