App/Hra.App/Controllers/GrupoController.cs
using Hra.App.Models;
using Hra.Application.DTO;
using Hra.Domain.Entity;
using Hra.Infraestructure.Data;
using Hra.Transversal.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hra.App.Controllers
{
    public class GrupoController : Controller
    {
        private readonly BAMBUContext context;
        private readonly IConstante constante;
        public GrupoController(BAMBUContext context, IConstante constante)
        {
            this.context = context;
            this.constante = constante;
        }
        // GET: GrupoController
        public async Task<ActionResult> Index(string pBuscar = "")
        {
            var lst = new List<ListarGrupoDto>();
            var qry = await (from x in context.Grupo
                             join vt in (context.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Taller)) on x.TallerId equals vt.ItemId
                             where x.Denominacion.Contains(pBuscar)
                             select new ListarGrupoDto
                             {
                                 GrupoId = x.GrupoId,
                                 Denominacion = x.Denominacion,
                                 FechaInicio = x.FechaInicio,
                                 Costo = x.Costo,
                                 TallerId = x.TallerId,
                                 Taller = vt.Denominacion
                             }).ToListAsync();

            if (!string.IsNullOrEmpty(pBuscar) && pBuscar.Trim().Length > 0)
                lst = await (from x in context.Grupo
                             join vt in (context.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Taller)) on x.TallerId equals vt.ItemId
                             where x.Denominacion.Contains(pBuscar)
                             select new ListarGrupoDto
                             {
                                 GrupoId = x.GrupoId,
                                 Denominacion = x.Denominacion,
                                 FechaInicio = x.FechaInicio,
                                 Costo = x.Costo,
                                 TallerId = x.TallerId,
                                 Taller = vt.Denominacion
                             }).ToListAsync();
            else
                lst = await (from x in context.Grupo.Take(20)
                             join vt in (context.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Taller)) on x.TallerId equals vt.ItemId
                             select new ListarGrupoDto
                             {
                                 GrupoId = x.GrupoId,
                                 Denominacion = x.Denominacion,
                                 FechaInicio = x.FechaInicio,
                                 Costo = x.Costo,
                                 TallerId = x.TallerId,
                                 Taller = vt.Denominacion
                             }).ToListAsync();
            return View(lst.OrderBy(x => x.TallerId));
        }

        // GET: GrupoController/Create
        public async Task<ActionResult> Create(int id = 0)
        {
            ViewBag.TokenApiPeru = constante.TokenApiPeru;
            var grupo = new Grupo();
            ViewBag.id = id;
            var lstMiembro = new List<ListarMiembroDto>();
            if (id > 0)
            {

                grupo = await context.Grupo.FindAsync(id);
                //grupo.Miembro = await context.Miembro.Include(x => x.Persona)
                //    .Where(x => x.GrupoId == id).ToListAsync();                
                lstMiembro = await (from x in context.Miembro
                                    join vt in (context.ValorTabla.Where(x => x.TablaId == Constante.Tabla.EstadoMiembro)) on x.EstadoId equals vt.ItemId
                                    join n in (context.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Nivel)) on x.NivelId equals n.ItemId
                                    where x.GrupoId == id
                                    select new ListarMiembroDto
                                    {
                                        MiembroId = x.MiembroId,
                                        PersonaId = x.PersonaId,
                                        Dni = x.Persona.NumeroDocumento,
                                        Miembro = x.Persona.NombreCompleto,
                                        Celular = x.Persona.Celular,
                                        Correo = x.Persona.Email,
                                        Grupo = x.Grupo.Denominacion,
                                        Nivel = n.Denominacion,
                                        Estado = vt.Denominacion,
                                        EstadoId = x.EstadoId,
                                        NivelId = x.NivelId,
                                        GrupoId = x.GrupoId
                                    }).OrderBy(x => x.Miembro).ToListAsync();
            }
            ViewBag.lstMiembro = lstMiembro;
            ViewBag.cboTaller = await context.ValorTabla.Where(x => x.TablaId == Constante.Tabla.Taller && x.ItemId > 0)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();
            string tallerid = grupo.TallerId.ToString();
            ViewBag.cboNivel = await context.ValorTabla
                .Where(x => x.TablaId == Constante.Tabla.Nivel && x.ItemId > 0 && x.Valor == tallerid)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();
            ViewBag.cboEstado = await context.ValorTabla.Where(x => x.TablaId == Constante.Tabla.EstadoMiembro && x.ItemId > 0)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.ItemId.ToString()
                }).ToListAsync();
            ViewBag.cboGrupo = await context.Grupo
                .Where(x => x.TallerId == grupo.TallerId)
                .Select(x => new SelectListItem
                {
                    Text = x.Denominacion,
                    Value = x.GrupoId.ToString()
                }).ToListAsync();
            return View(grupo);
        }

        // POST: GrupoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Grupo grupo)
        {
            try
            {
                if (grupo.GrupoId == 0)
                {
                    context.Grupo.Add(grupo);
                }
                else
                {
                    context.Grupo.Update(grupo);
                }
                await context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public async Task<ActionResult> AgregarMiembro(int pGrupoId, string pDni, string pPaterno,
            string pMaterno, string pNombres)
        {
            pDni = pDni.Trim();
            pPaterno = pPaterno.ToUpper();
            pMaterno = pMaterno.ToUpper();
            pNombres = pNombres.ToUpper();

            var persona = await context.Persona.FirstOrDefaultAsync(x => x.NumeroDocumento == pDni);
            var grupo = context.Grupo.Find(pGrupoId);
            if (persona == null)
            {
                persona = new Persona
                {
                    NumeroDocumento = pDni,
                    ApePaterno = pPaterno,
                    ApeMaterno = pMaterno,
                    Nombre = pNombres,
                    NombreCompleto = pPaterno + " " + pMaterno + " " + pNombres,
                    Sexo = "M",
                    Activo = true,
                    TipoAlimentacionId = 1,
                    FechaReg = DateTime.Now,
                    IndWari = false
                };
                context.Persona.Add(persona);
                await context.SaveChangesAsync();
            }
            if (grupo.TallerId == Constante.Taller.Wari)
            {
                persona.IndWari = true;
                await context.SaveChangesAsync();
            }

            var miembro = context.Miembro.FirstOrDefault(x => x.PersonaId == persona.PersonaId && x.GrupoId == pGrupoId);
            if (miembro == null)
            {
                string tallerid = grupo.TallerId.ToString();
                var nivel = context.ValorTabla.First(x => x.TablaId == Constante.Tabla.Nivel && x.Valor == tallerid);
                miembro = new Miembro
                {
                    PersonaId = persona.PersonaId,
                    GrupoId = pGrupoId,
                    Fecha = DateTime.Now,
                    EstadoId = Constante.EstadoPersona.Pendiente,
                    NivelId = nivel.ItemId
                };
                context.Miembro.Add(miembro);
                await context.SaveChangesAsync();
            }


            return RedirectToAction(nameof(Create), new { id = pGrupoId });
        }



        public async Task<ActionResult> EliminarMiembro(int pGrupoId, int pMiembroId)
        {
            var cliente = await context.Miembro.FindAsync(pMiembroId);

            if (cliente != null)
            {
                context.Miembro.Remove(cliente);
                await context.SaveChangesAsync();
            }
            var existewari = await context.Miembro.AnyAsync(x => x.PersonaId == cliente.PersonaId
            && x.Grupo.TallerId == Constante.Taller.Wari);

            var persona = await context.Persona.FindAsync(cliente.PersonaId);
            persona.IndWari = existewari;
            await context.SaveChangesAsync();

App/Hra.App/Controllers/RolController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hra.App.Controllers
{
    public class RolController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

App/Hra.App/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hra.App.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

App/Hra.App/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="es-pe">
<head>
        <meta charset="utf-8" />
        <title>Bambu</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="~/assets/images/favicon.ico">

        <link href="~/assets/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css">
        <link href="~/assets/libs/spectrum-colorpicker2/spectrum.min.css" rel="stylesheet" type="text/css">
        <link href="~/assets/libs/bootstrap-timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet" type="text/css">
        <link href="~/assets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="~/assets/libs/%40chenfengyuan/datepicker/datepicker.min.css">

        <link href="~/assets/libs/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css" />

        <link href="~/assets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
        <link href="~/assets/libs/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="~/assets/libs/toastr/build/toastr.min.css">
        <link href="~/assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />
    </head>
    <body data-topbar="light" data-layout="horizontal">
        <div id="layout-wrapper">
            <header id="page-topbar">
                <div class="navbar-header">
                    <div class="d-flex">
                        <!-- LOGO -->
                        <div class="navbar-brand-box">
                            <a href="@Url.Action("Index","Home")" class="logo logo-dark">
                                <span class="logo-sm">
                                    <img src="~/assets/images/logo-dark.png" alt="" height="60">
                                </span>
                                <span class="logo-lg">
                                    <img src="~/assets/images/logo-dark.png" alt="" height="65">
                                </span>
                            </a>

                            <a href="@Url.Action("Index","Home")" class="logo logo-light">
                                <span class="logo-sm">
                                    <img src="~/assets/images/logo-dark.png" alt="" height="60">
                                </span>
                                <span class="logo-lg">
                                    <img src="~/assets/images/logo-light.png" alt="" height="65">
                                </span>
                            </a>
                        </div>

                        <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light" data-bs-toggle="collapse" data-bs-target="#topnav-menu-content">
                            <i class="fa fa-fw fa-bars"></i>
                        </button>   
                        
                    </div>

                    <div class="d-flex"> 
                        <div class="dropdown d-none d-lg-inline-block ms-1">
                            <button type="button" class="btn header-item noti-icon waves-effect"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bx bx-customize"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                                <div class="px-lg-2">
                                    <div class="row g-0">
                                        <div class="col">
                                            <a class="dropdown-icon-item" href="#">
                                                <img src="~/assets/images/brands/github.png" alt="Github">
                                                <span>GitHub</span>
                                            </a>
                                        </div>
                                        <div class="col">
                                            <a class="dropdown-icon-item" href="#">
                                                <img src="~/assets/images/brands/bitbucket.png" alt="bitbucket">
                                                <span>Bitbucket</span>
                                            </a>
                                        </div>
                                        <div class="col">
                                            <a class="dropdown-icon-item" href="#">
                                                <img src="~/assets/images/brands/dribbble.png" alt="dribbble">
                                                <span>Dribbble</span>
                                            </a>
                                        </div>
                                    </div>                                    
                                </div>
                            </div>
                        </div>

                        <div class="dropdown d-none d-lg-inline-block ms-1">
                            <button type="button" class="btn header-item noti-icon waves-effect" data-bs-toggle="fullscreen">
                                <i class="bx bx-fullscreen"></i>
                            </button>
                        </div>
                                             

                        <div class="dropdown d-inline-block">
                            <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img class="rounded-circle header-profile-user" src="~/assets/images/users/avatar.jpg"
                                    alt="Header Avatar">
                                <span class="d-none d-xl-inline-block ms-1" key="t-henry">Usuario</span>
                                <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-end">
                                <!-- item-->
                                <a class="dropdown-item" href="#"><i class="bx bx-user font-size-16 align-middle me-1"></i> <span key="t-profile">Perfil</span></a>
                                <a class="dropdown-item" href="#"><i class="bx bx-lock-open font-size-16 align-middle me-1"></i> <span key="t-lock-screen">Bloquear Pantalla</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-danger" href="@Url.Action("Logout","Seguridad")"><i class="bx bx-power-off font-size-16 align-middle me-1 text-danger"></i> <span key="t-logout">Cerrar Sesión</span></a>
                            </div>
                        </div>
                       
                    </div>
                </div>
            </header>
    
            <div class="topnav">
                <div class="container-fluid">
                    <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

                        <div class="collapse navbar-collapse" id="topnav-menu-content">
                            <ul class="navbar-nav">

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-dashboard" role="button"
                                    >
                                        <i class="bx bx-home-circle me-2"></i><span key="t-dashboards">Seguridad</span> <div class="arrow-down"></div>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="topnav-dashboard">

                                        <a href="@Url.Action("Index","Usuario")" class="dropdown-item" key="t-default">Usuario</a>
                                        <a href="@Url.Action("Index","Rol")" class="dropdown-item" key="t-saas">Rol</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-dashboard" role="button"
                                    >
                                        <i class="bx bx-home-circle me-2"></i><span key="t-dashboards">Registros</span> <div class="arrow-down"></div>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="topnav-dashboard">
                                        <a href="@Url.Action("Index","Grupo")" class="dropdown-item" key="t-default">Grupo</a>
                                        <a href="@Url.Action("Listar","Cliente")" class="dropdown-item" key="t-default">Miembros</a>
                                    </div>
                                </li> 
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-dashboard" role="button"
                                    >
                                        <i class="bx bx-home-circle me-2"></i><span key="t-dashboards">Reportes</span> <div class="arrow-down"></div>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="topnav-dashboard">

                                        <a href="@Url.Action("Index","Uci")" class="dropdown-item" key="t-default">Ingreso1</a>
                                    </div>
                                </li>                                                              

                            </ul>
                        </div>
                    </nav>
                </div>
            </div>

            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">
                <div class="page-content">
                    <div class="container-fluid">
                        @RenderBody()                        
                    </div>
                </div> 
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                                <script>document.write(new Date().getFullYear())</script> © Bambu Coaching.
                            </div>
                            <div class="col-sm-6">
                                <div class="text-sm-end d-none d-sm-block">
                                    Desarrollado por Codea Peru
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        
        <div class="rightbar-overlay"></div>

        <script src="~/assets/libs/jquery/jquery.min.js"></script>
        <script src="~/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/assets/libs/metismenu/metisMenu.min.js"></script>
        <script src="~/assets/libs/simplebar/simplebar.min.js"></script>
        <script src="~/assets/libs/node-waves/waves.min.js"></script>
        <script src="~/assets/libs/select2/js/select2.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/i18n/es.js"></script>
        <script src="~/assets/libs/inputmask/min/jquery.inputmask.bundle.min.js"></script>
        <script src="~/assets/libs/toastr/build/toastr.min.js"></script>
        <script src="~/assets/libs/parsleyjs/parsley.min.js"></script>
        <script src="~/assets/libs/magnific-popup/jquery.magnific-popup.min.js"></script>

        <script src="~/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
        <script src="~/assets/libs/spectrum-colorpicker2/spectrum.min.js"></script>
        <script src="~/assets/libs/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
        <script src="~/assets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
        <script src="~/assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
        <script src="~/assets/libs/%40chenfengyuan/datepicker/datepicker.min.js"></script>

        <script src="~/assets/js/app.js"></script>
        <script src="~/js/ini.js"></script>
        <script src="~/js/parsley_es.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>

</html>